In [0]:
import numpy as np

In [5]:
!wget https://fmi-unibuc-ia.github.io/ia/Data/data_lab5.zip

--2020-05-06 07:20:55--  https://fmi-unibuc-ia.github.io/ia/Data/data_lab5.zip
Resolving fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)... 185.199.109.153, 185.199.111.153, 185.199.108.153, ...
Connecting to fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503740 (492K) [application/zip]
Saving to: ‘data_lab5.zip.4’

data_lab5.zip.4     100%[===================>] 491.93K  --.-KB/s    in 0.05s   

2020-05-06 07:20:55 (10.1 MB/s) - ‘data_lab5.zip.4’ saved [503740/503740]



In [6]:
!unzip data_lab5.zip

Archive:  data_lab5.zip
replace data/test_labels.npy? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: data/test_labels.npy    
  inflating: data/test_sentences.npy  
  inflating: data/training_labels.npy  
  inflating: data/training_sentences.npy  


In [0]:
train_data = np.load('data/training_sentences.npy', allow_pickle=True)
train_labels = np.load('data/training_labels.npy')

test_data = np.load('data/test_sentences.npy', allow_pickle=True)
test_labels = np.load('data/test_labels.npy')

In [8]:
train_data[0]

['Probably', 'not', 'still', 'going', 'over', 'some', 'stuff', 'here']

In [9]:
train_data[:10]

array([list(['Probably', 'not', 'still', 'going', 'over', 'some', 'stuff', 'here']),
       list(['I', 'HAVE', 'A', 'DATE', 'ON', 'SUNDAY', 'WITH', 'WILL']),
       list(['Thanks', '4', 'your', 'continued', 'support', 'Your', 'question', 'this', 'week', 'will', 'enter', 'u', 'in2', 'our', 'draw', '4', '£100', 'cash', 'Name', 'the', 'NEW', 'US', 'President', 'txt', 'ans', 'to', '80082']),
       list(['Dear', '0776xxxxxxx', 'Uve', 'been', 'invited', 'to', 'XCHAT', 'This', 'is', 'our', 'final', 'attempt', 'to', 'contact', 'u', 'Txt', 'CHAT', 'to', '86688', '150pMsgrcvdHGSuite3422LandsRowW1J6HL', 'LDN', '18yrs']),
       list(['I', 'sent', 'my', 'scores', 'to', 'sophas', 'and', 'i', 'had', 'to', 'do', 'secondary', 'application', 'for', 'a', 'few', 'schools', 'I', 'think', 'if', 'you', 'are', 'thinking', 'of', 'applying', 'do', 'a', 'research', 'on', 'cost', 'also', 'Contact', 'joke', 'ogunrinde', 'her', 'school', 'is', 'one', 'me', 'the', 'less', 'expensive', 'ones']),
       list(['Koth

In [0]:
# Modelul bag-of-words

In [0]:
# 3. Definiți clasa BagOfWords în al cărui constructor se inițializează vocabularul (un
# dicționar gol). În cadrul ei implementați metoda build_vocabulary(self, data) care
# primește ca parametru o listă de mesaje(listă de liste de strings) și construiește
# vocabularul pe baza acesteia. Cheile dicționarului sunt reprezentate de cuvintele din
# eseuri, iar valorile de id-urile unice atribuite cuvintelor. Pe lângă vocabularul pe care-l
# construiți, rețineți și o listă cu cuvintele în ordinea adăugării în vocabular.
# Afișați dimensiunea vocabularul construit (9522).

class BagOfWords:

    def __init__(self):
        self.vocab = {} # dictionar cuvant -> idx
        self.words = [] # lista de cuvinte

    def build_vocabulary(self, train_data):
        for sentence in train_data:
            for word in sentence:
                if word not in self.vocab:
                    self.vocab[word] = len(self.words)
                    self.words.append(word)
        return len(self.words)

    # 4. Definiți metoda get_features(self, data) care primește ca parametru o listă de
    # mesaje de dimensiune 𝑛𝑢𝑚_𝑠𝑎𝑚𝑝𝑙𝑒𝑠(listă de liste de strings) și returnează o matrice
    # de dimensiune (𝑛𝑢𝑚_𝑠𝑎𝑚𝑝𝑙𝑒𝑠 x 𝑑𝑖𝑐𝑡𝑖𝑜𝑛𝑎𝑟𝑦_𝑙𝑒𝑛𝑔𝑡ℎ) definită astfel:

    def get_features(self, data):
        result = np.zeros((data.shape[0], len(self.words)),dtype='uint16')
        for idx, sentence in enumerate(data):
            for word in sentence:
                if word in self.vocab:
                    result[idx, self.vocab[word]] += 1
        return result

In [11]:
bow = BagOfWords()
print(bow.build_vocabulary(train_data))

9522


In [12]:
train_features = bow.get_features(train_data)

print(train_features.shape)
print(train_features)

(3734, 9522)
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [13]:
print(train_data[1])
print(train_features[1][:20])

['I', 'HAVE', 'A', 'DATE', 'ON', 'SUNDAY', 'WITH', 'WILL']
[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]


In [14]:
print(train_data[102])
print(train_features[102][:20])

['Babe', 'U', 'want', 'me', 'dont', 'u', 'baby', 'Im', 'nasty', 'and', 'have', 'a', 'thing', '4', 'filthyguys', 'Fancy', 'a', 'rude', 'time', 'with', 'a', 'sexy', 'bitch', 'How', 'about', 'we', 'go', 'slo', 'n', 'hard', 'Txt', 'XXX', 'SLO4msgs']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


In [15]:
print([(x, bow.vocab[x]) for x in train_data[102]])

[('Babe', 799), ('U', 168), ('want', 800), ('me', 90), ('dont', 247), ('u', 27), ('baby', 801), ('Im', 334), ('nasty', 802), ('and', 63), ('have', 471), ('a', 70), ('thing', 482), ('4', 17), ('filthyguys', 803), ('Fancy', 804), ('a', 70), ('rude', 805), ('time', 145), ('with', 195), ('a', 70), ('sexy', 806), ('bitch', 807), ('How', 414), ('about', 189), ('we', 268), ('go', 307), ('slo', 808), ('n', 542), ('hard', 809), ('Txt', 53), ('XXX', 810), ('SLO4msgs', 811)]


In [16]:
test_features = bow.get_features(test_data)

print(test_features.shape)
print(test_features)

(1840, 9522)
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
# Normalizarea datelor 

In [0]:
# 2. Definiți funcția normalize_data(train_data, test_data, type=None) care primește ca
# parametri datele de antrenare, respectiv de testare și tipul de normalizare ({None,
# ‘standard’, ‘min_max’, ‘l1’, ‘l2’}) și întoarce aceste date normalizate. 

from sklearn import preprocessing

def normalize_data(train_data, test_data, type=None):
    scaler = None
    if type == 'standard':
        scaler = preprocessing.StandardScaler()

    elif type == 'min_max':
        scaler = preprocessing.MinMaxScaler()

    elif type == 'l1' or type == 'l2':
        scaler = preprocessing.Normalizer(norm=type)

    if scaler is not None:
        scaler.fit(train_data)
        scaled_train_data = scaler.transform(train_data)
        scaled_test_data = scaler.transform(test_data)
        return scaled_train_data, scaled_test_data
    else:
        return train_data, test_data

In [18]:
# 5. Cu ajutorul funcțiilor definite anterior, obțineți reprezentările BOW pentru mulțimea de
# antrenare și testare, apoi normalizați-le folosind norma “L2”.

test_features = bow.get_features(test_data)

print(test_features.shape)
print(test_features)

(1840, 9522)
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
norm_train_features, norm_test_features = normalize_data(train_features, test_features, 'l2')

norm_train_features

array([[0.35355339, 0.35355339, 0.35355339, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.19611614, 0.19611614,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.33333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [32]:
!wget https://fmi-unibuc-ia.github.io/ia/Data/Lab%205%20-%20toy%20example%20-%20SVM.zip

--2020-05-06 07:35:45--  https://fmi-unibuc-ia.github.io/ia/Data/Lab%205%20-%20toy%20example%20-%20SVM.zip
Resolving fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)... 185.199.111.153, 185.199.108.153, 185.199.110.153, ...
Connecting to fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34422 (34K) [application/zip]
Saving to: ‘Lab 5 - toy example - SVM.zip.1’

Lab 5 - toy example 100%[===================>]  33.62K  --.-KB/s    in 0.007s  

2020-05-06 07:35:45 (4.65 MB/s) - ‘Lab 5 - toy example - SVM.zip.1’ saved [34422/34422]



In [38]:
!unzip 'Lab 5 - toy example - SVM.zip'

Archive:  Lab 5 - toy example - SVM.zip
replace data/svm_train_data.npy? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: data/svm_train_data.npy  
  inflating: data/svm_train_labels.npy  
  inflating: Lab 5 - toy example - SVM.ipynb  


In [0]:
# 1. Descărcați arhiva de aici și observați cum funcționează modelul SVM.
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

svm_train_data   = np.load('data/svm_train_data.npy', allow_pickle=True)
svm_train_labels = np.load('data/svm_train_labels.npy', allow_pickle=True).astype(np.bool)

X_train, X_valid, y_train, y_valid = train_test_split(svm_train_data, svm_train_labels, test_size=0.2, random_state=42)

In [51]:
svc = SVC(0.1, 'linear')
svc.fit(X_train, y_train)
svc.score(X_valid, y_valid)

1.0

In [0]:
# 6.
from sklearn import svm

model = svm.SVC(C=1.0, kernel='linear')
model.fit(norm_train_features, train_labels)

In [55]:
#  Calculați acuratețea și F1-score pentrumulțimea de testare

from sklearn.metrics import accuracy_score, f1_score, classification_report

test_preds = model.predict(norm_test_features)
accuracy_score(test_labels, test_preds)
f1_score(test_labels, test_preds)
print(classification_report(test_labels, test_preds))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1585
           1       0.98      0.91      0.94       255

    accuracy                           0.98      1840
   macro avg       0.98      0.95      0.97      1840
weighted avg       0.98      0.98      0.98      1840



In [59]:
# Afișați cele mai negative (spam) 10 cuvinte și cele mai pozitive (non-spam) 10 cuvinte.

import numpy as np

weights = np.squeeze(model.coef_)
indexes = np.argsort(weights)
words = np.array(bow.words)
print('NEGATIVE', words[indexes[-10:]]) # Spam words
print('POSITIVE', words[indexes[:10]]) # Good words

NEGATIVE ['Text' 'To' 'mobile' 'CALL' 'FREE' 'txt' '&' 'Call' 'Txt' 'STOP']
POSITIVE ['&lt#&gt' 'me' 'i' 'Going' 'him' 'Ok' 'I' 'Ill' 'my' 'Im']


In [62]:
# Antrenati un SVM pe datele de mai sus folosind urmatoarele valori pt C
for C in [0.1, 0.3, 0.7]:
    model = svm.SVC(C=C, kernel='linear')
    model.fit(norm_train_features, train_labels)

    #  Calculați acuratețea și F1-score pentrumulțimea de testare

    from sklearn.metrics import accuracy_score, f1_score, classification_report

    test_preds = model.predict(norm_test_features)
    # print(accuracy_score(test_labels, test_preds))
    # print(f1_score(test_labels, test_preds))
    print(C)
    print(classification_report(test_labels, test_preds))

0.1
              precision    recall  f1-score   support

           0       0.91      1.00      0.95      1585
           1       1.00      0.40      0.57       255

    accuracy                           0.92      1840
   macro avg       0.96      0.70      0.76      1840
weighted avg       0.92      0.92      0.90      1840

0.3
              precision    recall  f1-score   support

           0       0.97      1.00      0.99      1585
           1       1.00      0.82      0.90       255

    accuracy                           0.97      1840
   macro avg       0.98      0.91      0.94      1840
weighted avg       0.97      0.97      0.97      1840

0.7
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1585
           1       0.97      0.89      0.93       255

    accuracy                           0.98      1840
   macro avg       0.98      0.94      0.96      1840
weighted avg       0.98      0.98      0.98      1840



In [61]:
# Antrenati un SVM pe datele de mai sus folosind urmatoarele valori pt kernel
for l in ['rbf','poly']:

    model = svm.SVC(C=1.0, kernel=l)
    model.fit(norm_train_features, train_labels)

    #  Calculați acuratețea și F1-score pentrumulțimea de testare

    from sklearn.metrics import accuracy_score, f1_score, classification_report

    test_preds = model.predict(norm_test_features)
    
    print(C)
    print(classification_report(test_labels, test_preds))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1585
           1       1.00      0.87      0.93       255

    accuracy                           0.98      1840
   macro avg       0.99      0.93      0.96      1840
weighted avg       0.98      0.98      0.98      1840

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1585
           1       1.00      0.61      0.76       255

    accuracy                           0.95      1840
   macro avg       0.97      0.81      0.86      1840
weighted avg       0.95      0.95      0.94      1840



In [0]:
# Audio file

In [0]:
# sa facem specto-grame input la un cnn -> spectrogram + CNN
# neural network audio classification -> raw + RNN (cel mai greu)
# fft audio -> histograma (cea mai simpla),  pune in binuri -> FFT + Linear classifier (cel mai usor)

# SA NU UIT DE NORMALIZARI