In [0]:
import numpy as np

In [3]:
!wget https://fmi-unibuc-ia.github.io/ia/Data/data_lab5.zip

--2020-04-29 07:28:40--  https://fmi-unibuc-ia.github.io/ia/Data/data_lab5.zip
Resolving fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)... 185.199.111.153, 185.199.110.153, 185.199.108.153, ...
Connecting to fmi-unibuc-ia.github.io (fmi-unibuc-ia.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503740 (492K) [application/zip]
Saving to: ‘data_lab5.zip’

data_lab5.zip       100%[===================>] 491.93K  --.-KB/s    in 0.04s   

2020-04-29 07:28:40 (11.1 MB/s) - ‘data_lab5.zip’ saved [503740/503740]



In [4]:
!unzip data_lab5.zip

Archive:  data_lab5.zip
  inflating: data/test_labels.npy    
  inflating: data/test_sentences.npy  
  inflating: data/training_labels.npy  
  inflating: data/training_sentences.npy  


In [0]:
train_data = np.load('data/training_sentences.npy', allow_pickle=True)
train_labels = np.load('data/training_labels.npy')

test_data = np.load('data/test_sentences.npy', allow_pickle=True)
test_labels = np.load('data/test_labels.npy')

In [6]:
train_data[0]

['Probably', 'not', 'still', 'going', 'over', 'some', 'stuff', 'here']

In [25]:
train_data[:10]

array([list(['Probably', 'not', 'still', 'going', 'over', 'some', 'stuff', 'here']),
       list(['I', 'HAVE', 'A', 'DATE', 'ON', 'SUNDAY', 'WITH', 'WILL']),
       list(['Thanks', '4', 'your', 'continued', 'support', 'Your', 'question', 'this', 'week', 'will', 'enter', 'u', 'in2', 'our', 'draw', '4', '£100', 'cash', 'Name', 'the', 'NEW', 'US', 'President', 'txt', 'ans', 'to', '80082']),
       list(['Dear', '0776xxxxxxx', 'Uve', 'been', 'invited', 'to', 'XCHAT', 'This', 'is', 'our', 'final', 'attempt', 'to', 'contact', 'u', 'Txt', 'CHAT', 'to', '86688', '150pMsgrcvdHGSuite3422LandsRowW1J6HL', 'LDN', '18yrs']),
       list(['I', 'sent', 'my', 'scores', 'to', 'sophas', 'and', 'i', 'had', 'to', 'do', 'secondary', 'application', 'for', 'a', 'few', 'schools', 'I', 'think', 'if', 'you', 'are', 'thinking', 'of', 'applying', 'do', 'a', 'research', 'on', 'cost', 'also', 'Contact', 'joke', 'ogunrinde', 'her', 'school', 'is', 'one', 'me', 'the', 'less', 'expensive', 'ones']),
       list(['Koth

In [0]:
# Modelul bag-of-words

In [0]:
# 3. Definiți clasa BagOfWords în al cărui constructor se inițializează vocabularul (un
# dicționar gol). În cadrul ei implementați metoda build_vocabulary(self, data) care
# primește ca parametru o listă de mesaje(listă de liste de strings) și construiește
# vocabularul pe baza acesteia. Cheile dicționarului sunt reprezentate de cuvintele din
# eseuri, iar valorile de id-urile unice atribuite cuvintelor. Pe lângă vocabularul pe care-l
# construiți, rețineți și o listă cu cuvintele în ordinea adăugării în vocabular.
# Afișați dimensiunea vocabularul construit (9522).

class BagOfWords:

    def __init__(self):
        self.vocab = {} # dictionar cuvant -> idx
        self.words = [] # lista de cuvinte

    def build_vocabulary(self, train_data):
        for sentence in train_data:
            for word in sentence:
                if word not in self.vocab:
                    self.vocab[word] = len(self.words)
                    self.words.append(word)
        return len(self.words)

    # 4. Definiți metoda get_features(self, data) care primește ca parametru o listă de
    # mesaje de dimensiune 𝑛𝑢𝑚_𝑠𝑎𝑚𝑝𝑙𝑒𝑠(listă de liste de strings) și returnează o matrice
    # de dimensiune (𝑛𝑢𝑚_𝑠𝑎𝑚𝑝𝑙𝑒𝑠 x 𝑑𝑖𝑐𝑡𝑖𝑜𝑛𝑎𝑟𝑦_𝑙𝑒𝑛𝑔𝑡ℎ) definită astfel:

    def get_features(self, data):
        result = np.zeros((data.shape[0], len(self.words)),dtype='uint16')
        for idx, sentence in enumerate(data):
            for word in sentence:
                if word in self.vocab:
                    result[idx, self.vocab[word]] += 1
        return result

In [14]:
bow = BagOfWords()
print(bow.build_vocabulary(train_data))

9522


In [15]:
train_features = bow.get_features(train_data)

print(train_features.shape)
print(train_features)

(3734, 9522)
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [17]:
print(train_data[1])
print(train_features[1][:20])

['I', 'HAVE', 'A', 'DATE', 'ON', 'SUNDAY', 'WITH', 'WILL']
[0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]


In [21]:
print(train_data[102])
print(train_features[102][:20])

['Babe', 'U', 'want', 'me', 'dont', 'u', 'baby', 'Im', 'nasty', 'and', 'have', 'a', 'thing', '4', 'filthyguys', 'Fancy', 'a', 'rude', 'time', 'with', 'a', 'sexy', 'bitch', 'How', 'about', 'we', 'go', 'slo', 'n', 'hard', 'Txt', 'XXX', 'SLO4msgs']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


In [22]:
print([(x, bow.vocab[x]) for x in train_data[102]])

[('Babe', 799), ('U', 168), ('want', 800), ('me', 90), ('dont', 247), ('u', 27), ('baby', 801), ('Im', 334), ('nasty', 802), ('and', 63), ('have', 471), ('a', 70), ('thing', 482), ('4', 17), ('filthyguys', 803), ('Fancy', 804), ('a', 70), ('rude', 805), ('time', 145), ('with', 195), ('a', 70), ('sexy', 806), ('bitch', 807), ('How', 414), ('about', 189), ('we', 268), ('go', 307), ('slo', 808), ('n', 542), ('hard', 809), ('Txt', 53), ('XXX', 810), ('SLO4msgs', 811)]


In [24]:
test_features = bow.get_features(test_data)

print(test_features.shape)
print(test_features)

(1840, 9522)
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
# Normalizarea datelor 

In [0]:
# 2. Definiți funcția normalize_data(train_data, test_data, type=None) care primește ca
# parametri datele de antrenare, respectiv de testare și tipul de normalizare ({None,
# ‘standard’, ‘min_max’, ‘l1’, ‘l2’}) și întoarce aceste date normalizate. 

from sklearn import preprocessing

def normalize_data(train_data, test_data, type=None):
    scaler = None
    if type == 'standard':
        scaler = preprocessing.StandardScaler()

    elif type == 'min_max':
        scaler = preprocessing.MinMaxScaler()

    elif type == 'l1' or type == 'l2':
        scaler = preprocessing.Normalizer(norm=type)

    if scaler is not None:
        scaler.fit(train_data)
        scaled_train_data = scaler.transform(train_data)
        scaled_test_data = scaler.transform(test_data)
        return scaled_train_data, scaled_test_data
    else:
        return train_data, test_data

In [29]:
# 5. Cu ajutorul funcțiilor definite anterior, obțineți reprezentările BOW pentru mulțimea de
# antrenare și testare, apoi normalizați-le folosind norma “L2”.

test_features = bow.get_features(test_data)

print(test_features.shape)
print(test_features)

(1840, 9522)
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
norm_train_features, norm_test_features = normalize_data(train_features, test_features, 'l2')

norm_train_features

array([[0.35355339, 0.35355339, 0.35355339, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.19611614, 0.19611614,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.33333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])